version: '3'

services:
  server:
    build:
        context: ./server
        dockerfile: Dockerfile.dev
    volumes:
      - ./server:/api
    ports:
      - 8000:8000
  web:
    build:
        context: ./web
        dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app
    ports:
      - 8080:8080
