version: '3'

services:
  server:
    build: ./server
    volumes:
      - ./server:/api
    ports:
      - 8000:8000
  web:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - 8080:8080
