FROM node:11.1 as build-stage

WORKDIR /app
COPY . .
RUN yarn install
RUN yarn run build

FROM nginx:1.13.12 as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
